apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-person-svc-api
  name: udaconnect-person-svc-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30003
  selector:
    service: udaconnect-person-svc-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-person-svc-api
  name: udaconnect-person-svc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-person-svc-api
  template:
    metadata:
      labels:
        service: udaconnect-person-svc-api
    spec:
      containers:
      - image: jarich/udaconnect-person-svc-api:v1.03
        name: udaconnect-person-svc-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
