apiVersion: v1
data:
  KAFKA_SERVER: "kafka-release.default.svc.cluster.local"
  KAFKA_PORT: "9092"
  KAFKA_TOPIC: "test"
  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: "30002"
kind: ConfigMap
metadata:
  name: kafka-prod-configmap