apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-person-location-esvc-api
  name: udaconnect-person-location-esvc-api
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30007
  selector:
    service: udaconnect-person-location-esvc-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-person-location-esvc-api
  name: udaconnect-person-location-esvc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-person-location-esvc-api
  template:
    metadata:
      labels:
        service: udaconnect-person-location-esvc-api
    spec:
      containers:
      - image: jarich/person-location-event-svc:v1.01
        name: udaconnect-person-location-esvc-api
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: person-location-event-map
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: person-location-event-map
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always
